### ISSUE TITLE
Define a version scheme

### ISSUE THREAD

**Issue by brixen** [dependent/dependencies#3]
This effort would essentially be creating an interoperability standard, and as such, should have a carefully chosen versioning scheme.

I personally would not consider something like SemVer effective here, so I want to raise the issue and hopefully preserve some space for discussion.

There are version schemes for standards that we can look to for insight, but we shouldn't feel compelled to adopt something just because it exists, without consideration for whether it serves the goals of the project.

**Comment by aj-foster** [comment]
Could you elaborate your thoughts on the ineffectiveness of SemVer?

**Comment by olivierlacan** [comment]
@brixen I mechanically adopted SemVer because I use my http://keepachangelog.com/ a template for versions. Can you explain why it wouldn't be effective here specifically?

**Comment by olivierlacan** [comment]
I definitely want to find a sustainable version scheme especially to allow for translation of documentation though. So the sooner we can nail this down the better.

**Comment by brixen** [comment]
I don't see how to map SemVer expectations to something like this, a standard for interoperability. For example, what is a "bug", and by extension, what is a "bug" fix?

I'd suggest using a single monotonically increasing number as the simplest, most direct way to signal which version.

**Comment by aj-foster** [comment]
Trying to think through what a typical release might look like. Just "thinking aloud" here:
- Bug fixes... well, if I contribute at all, you can bet on needing some of those.
- Minor versions could relate to adding functionality (i.e. it now supports **x** language / resolver).
- Major / breaking changes might happen if there are changes to the syntax, default resolver (see discussion in #6), or something along those lines.

While I don't like the argument that "everyone else uses it", I do like the idea that SemVer is fairly widespread and well-understood. As a user, it makes my life easier if the version number tells me (for example) that only bug fixes - and no breaking changes - are included in a particular release.
